### ISSUE TITLE
Бесконечно постит состояния всех зарегистрированных датчиков

### ISSUE THREAD

**Issue by agsochi** [andrey-yantsen/wb-mqtt-astra#1]
Сегодня случился интересный случай, на Wirenboard 3.5 перестали работать датчики 1w, радио модуль, и не менялись состояния датчиков wb-mqtt-astra.
Подписался на все топики - оказалось что wb-mqtt-astra беспрерывно постит состояние всех датчиков с такой скоростью, что WB не справился с их обработкой и перестали работать другие службы WB.
Перезапуск  wb-mqtt-astra не помог, помогла только перезагрузка Астра-РИ-М по питанию.

**Comment by worried-networking** [comment]
Такая фигня бывает, если в очереди РИ-М скапливается много сообщений, из-за этого демон не успевает за отведённое время отправить на РИ-М команду для удаления переданных сообщений. В итоге эти 10-20-30 событий крутятся в бесконечном цикле.
Долго у тебя демон был запущен до этого? Всё стабильно работало, положенные задачи выполнялись?

**Comment by agsochi** [comment]
Да, все было замечательно, правда где-то несколько дней назад перезагружал WB (переносил роутер и свитч).

**Comment by worried-networking** [comment]
РИ-М при этом работал? Сколько примерно по времени связи не было между WB и РИ-М?

**Comment by agsochi** [comment]
Может Астру подключить реле WB и использовать это реле как watchdog?

**Comment by worried-networking** [comment]
Ну звучит как самый простой вариант. Со своей стороны могу только сделать, чтобы демон падал с ошибкой, если с РИ-М 10+ раз подряд приходит один и тот же набор событий.

**Comment by agsochi** [comment]
> РИ-М при этом работал? Сколько примерно по времени связи не было между WB и РИ-М?
РИ-М работал всё время, случилось ночью в 2 часа, заметил в 8 утра.

> Со своей стороны могу только сделать, чтобы демон падал с ошибкой, если с РИ-М 10+ раз подряд приходит один и тот же набор событий.

Вот я и хотел спросить как проще обойти такие случаи. 
Если демон упадет, нужно проверять его чем-то, запущен-ли и если не запущен - перед запуском передернуть питание?

**Comment by agsochi** [comment]
И получается нельзя чтобы РИ-М работала без запущенного демона wb-mqtt-astra?

**Comment by worried-networking** [comment]
Да, при запуске демона лучше всего перезагрузить РИ-М. Можно сделать, чтобы wb-mqtt-astra при запуске/выключении отправлял соответствующее сообщение в mqtt.

**Comment by agsochi** [comment]
Это то что нужно, через реле как раз удобно будет сделать.

**Comment by agsochi** [comment]
Тогда и демон можно не убивать, просто сообщение в топик

**Comment by worried-networking** [comment]
Запушил версию 0.5.4 — при запуске демона постит `1` (non-retained) в канал `/devices/wb_mqtt_astra/status`. Этого достаточно? С обнулением при отключении — проблемы пока :(

**Comment by agsochi** [comment]
Думаю да. Спасибо.
