### ISSUE TITLE
Не постит в топик `/devices/wb_mqtt_astra/status`

### ISSUE THREAD

**Issue by agsochi** [andrey-yantsen/wb-mqtt-astra#2]
Ничего не постит ни при запуске, ни при остановке демона.
0.5.4

**Comment by worried-networking** [comment]
Плодишь тут задачи, в старой бы просто написал :) Да, косяк. Попробуй v0.5.5 и топик `/devices/astra_1/controls/starting`.

**Comment by worried-networking** [comment]
В этот раз проверил — сообщение приходит. В идеале нужно после получения этого сообщения пару секунд подождать, чтобы демон провёл первичный опрос РИ-Ма, и потом можно его перезагружать.
