### ISSUE TITLE
Проблема с астрой РИМ

### ISSUE THREAD

**Issue by Deepinsideyou** [andrey-yantsen/wb-mqtt-astra#4]
Добрый день!

Проблема с AStra. до определенного момента все работало хорошо. начал копаться с wb-mqtt-serial  - проблемы со связью одного блока wb-mr14 и отвалились все датчики.  Думал сбил канал - провобовал во всех вариантах 1-2-3, перезапускал - не работают датчики... что посоветуете?

<script src="https://gist.github.com/Deepinsideyou/293f8ae9026bb7f3ffff8a78df33c1bf.js"></script>

**Comment by worried-networking** [comment]
Нужно больше подробностей — судя по логу обмен данными с РИ-М идёт. wb-mqtt-serial точно не слушает тот же порт, что и wb-mqtt-astra?
Для начала — попробуйте повторить регистрацию одного датчика и проверить его работу. Если что-то пойдёт не так — приложите лог, в рамках которого вы запускаете режим регистрации датчиков, регистрируете датчик и "тестируете" его (т.е. замыкаете контакты на датчике протечки, курите около датчика дыма и т.п.).

**Comment by Deepinsideyou** [comment]
переключил на 1 канал радио. стер все датчики и перегистировал. задрыгалось. спасибо
