### ISSUE TITLE
astra после перезагрузки не отвечает

### ISSUE THREAD

**Issue by Deepinsideyou** [andrey-yantsen/wb-mqtt-astra#5]
<script src="https://gist.github.com/Deepinsideyou/259439e74596592786c766743c6bf4d4.js"></script>

после перезагрузки опять таже проблема - датчики астры не видно. состояние last event меняется, но  channel 1 не срабатывает

**Comment by worried-networking** [comment]
Больше подробностей. Я вижу в логе такую строчку:
```
INFO: 2018/02/25 19:53:38 Received event astra_l.EventSStateOtherWithTemperature {EventSStateOtherBase:{EventSStateBase:{EventNoLink:{sensor:{Id:6 Type:{id:12 Name:RIM IK (Astra-5131)}} RSSI:44 IsNoLink:false isTestEvent:false} Noise:100} PowerOn:0 Efficiency:0 Tamper:0 Psu1Failure:0 Channel1:1 Channel2:0 Psu2Failure:0} Temperature:23}
```
В ней указано `Channel1:1`, т.е. датчик сработал.

**Comment by worried-networking** [comment]
BTW, почему вы добавляете в сообщения ссылку на лог-файл вот таким странным и кривым способом?
```
<script src="https://gist.github.com/Deepinsideyou/259439e74596592786c766743c6bf4d4.js"></script>
```

**Comment by Deepinsideyou** [comment]
а как ее еще добавлять то? по ссылке в Gist скопировал в клипбоард потом сюда

**Comment by worried-networking** [comment]
А, понятно. Вы копируете ссылку для встраивания в вэб-страницу, нужна просто ссылка, по которой откроется лог. Например тот же самый урл, который у вас в адресной строке браузера. Либо нужно в дропдауне выбрать `share`, вместо `embed`, и потом уже копировать.

**Comment by Deepinsideyou** [comment]
ни разу не пользовался GIST, только копировал и компилировал с github.

вообщем с удивлением обнаружил что датчик SMK самый дальний работает. остальные почему то нет.  я даже не знаю каких подробностей вам дать. просто перестали работать скрипты. в wirenboard/devices нет сработки датчиков.

**Comment by worried-networking** [comment]
На датчиках появилась галочка IsNoLink / Psu1Failure? Хоть что-нибудь? Или они в интерфейсе отображаются как ни чём ни бывало?
Тут 2 варианта — либо РИ-М потерял связь с датчиками, и в этом случае активируется одна из указанных выше галочек, либо датчики каким-то волшебным образом удалились из памяти РИ-Ма. Последнее могло произойти если вы каким-то образом нажали `delete` рядом с датчиком в интерфейсе WB.
Попробуйте просто вытащить-вставить батарейку у одного из датчиков. Если ничего не изменится — повторите регистрацию.

**Comment by worried-networking** [comment]
Время появления IsNoLink зависит от периода контроля, это настройка `control_time`, которая указывается, кажется, в минутах.

**Comment by Deepinsideyou** [comment]
delete не нажимал. просто контроллер перегрузил
isnolink не горит
Last event time обновляется
но сработки нет =(((

**Comment by Deepinsideyou** [comment]
в логах пишет ERROR:  Got Response

**Comment by worried-networking** [comment]
> просто контроллер перегрузил

Если речь идёт про WB, то перезагрузка контроллера на Астру никак повлиять не могла, т.к. вся привязка датчиков хранится в её энергонезависимой памяти. Единственное, что могло случиться — это переполнение памяти РИ-М, но в таком бы случае события поступали непрерывно, но этого не происходит.

> Last event time обновляется

Мне нужен новый лог. В том, что прислали вы, есть события только от одного датчика — Астра-5131, датчик №6. И это событие срабатывания датчика. Нужно выбрать какой-нибудь датчик, который сейчас не срабатывает, и у которого можно легко изменить состояние — например СМК или датчик протечки, затем включить демон с отладочным логированием, несколько раз активировать и деактивировать датчик, с паузой секунд по 5-10 между действиями, и затем выслать лог. Вместе с этим логом нужно указать, что именно вы делали, и с каким датчиком.

> в логах пишет ERROR: Got Response

Забыл убрать отладочное сообщение в версии 0.5.8, можете обновиться до 0.5.9, и оно исчезнет.

**Comment by Deepinsideyou** [comment]
обновился. перезагрузился. загрузка astra на уровне 30% процессор.
кильнул. пошел смотреть скрипты - RPC error.
сделал /etc/init.d/wb-rules force-reload
запустил астру и все заморгало. хз что такое
